import { Address } from "./Address";
import { PropertyType } from "./enums/PropertyType";
import { Status } from "./enums/Status";
import { Visibility } from "./enums/Visibility";
import { Financial } from "./Financial";
import { GoogleMapOption } from "./GoogleMapOption";
import { Lease } from "./Lease";
import { Physical } from "./Physical";
import { PriceVisibility } from "./PriceVisibility";
import { Resources } from "./Resources";
import { Score } from "./Score";

export interface Property {
    id: number;
    accountId: number;
    buyerAccountId: number | null;
    buyerUserId: number | null;
    externalId: null;
    programId: null;
    isDwellCertified: boolean;
    isAllowOffer: boolean;
    isAllowPreview: boolean;
    isFeatured: boolean;
    isRentGuaranteed: boolean;
    allowRentGuaranteedOptout: boolean;
    isSecuritized: boolean;
    isHot: boolean;
    isNew: boolean;
    isBargain: boolean | null;
    isDiligenceVaultUnlocked: boolean;
    isPropertyManagerOfferRetain: boolean | null;
    isHoa: boolean | null;
    hasAudio: boolean;
    hasDiligenceVaultDocuments: boolean;
    market: number;
    daysOnMarket: number | null;
    latitude: number | null;
    longitude: number | null;
    propertyName: null;
    description: null | string;
    highlights: null;
    mainImageUrl: null | string;
    personalProperties: null;
    diligenceVaultSummary: null | string;
    featuredReason: null;
    status: Status;
    allowedFundingTypes: null | string;
    allowableSaleTypes: null | string;
    visibility: Visibility;
    priceVisibility: PriceVisibility;
    propertyType: PropertyType;
    certificationLevel: null | string;
    escrowClosingDate: null | string;
    address: Address;
    financial: Financial | null;
    physical: Physical | null;
    score: Score | null;
    valuation: { [key: string]: number | null } | null;
    resources: Resources | null;
    manager: null;
    seller: null;
    sellerBroker: null;
    hoa: null;
    lease: Lease | null;
    diligences: any[] | null;
    googleMapOption: GoogleMapOption | null;
    inspectionType: null;
}