CREATE TABLE [dbo].[Lease] (
    [Id]                                      INT           IDENTITY (1, 1) NOT NULL,
    [LeaseSummary_Occupancy]                  NVARCHAR (50) NULL,
    [LeaseSummary_LeasingStatus]              NVARCHAR (50) NULL,
    [LeaseSummary_MarketedRent]               MONEY         NULL,
    [LeaseSummary_PaymentStatus]              NVARCHAR (50) NULL,
    [LeaseSummary_LeaseStartDate]             DATETIME      NULL,
    [LeaseSummary_LeaseEndDate]               DATETIME      NULL,
    [LeaseSummary_MonthlyRent]                MONEY         NULL,
    [LeaseSummary_SecurityDepositAmount]      MONEY         NULL,
    [LeaseSummary_HasPet]                     BIT           NULL,
    [LeaseSummary_PetFeeAmount]               MONEY         NULL,
    [LeaseSummary_IsPetsDeposit]              BIT           NULL,
    [LeaseSummary_PetsDepositAmount]          MONEY         NULL,
    [LeaseSummary_IsLeaseConcessions]         BIT           NULL,
    [LeaseSummary_IsRentersInsuranceRequired] BIT           NULL,
    [LeaseSummary_IsSection8]                 BIT           NULL,
    [LeaseSummary_IsTenantBackgroundChecked]  BIT           NULL,
    [LeaseSummary_IsTenantIncomeAbove3x]      BIT           NULL,
    [LeaseSummary_IsTenantMayTerminateEarly]  BIT           NULL,
    [LeaseSummary_IsTenantPurchaseOption]     BIT           NULL,
    [UtilitiesOwnership_Electric]             NVARCHAR (50) NULL,
    [UtilitiesOwnership_Gas]                  NVARCHAR (50) NULL,
    [UtilitiesOwnership_Water]                NVARCHAR (50) NULL,
    [UtilitiesOwnership_Garbage]              NVARCHAR (50) NULL,
    [UtilitiesOwnership_Pool]                 NVARCHAR (50) NULL,
    [UtilitiesOwnership_Landscaping]          NVARCHAR (50) NULL,
    [UtilitiesOwnership_PestControl]          NVARCHAR (50) NULL,
    [ApplianceOwnership_Refrigerator]         NVARCHAR (50) NULL,
    [ApplianceOwnership_Dishwasher]           NVARCHAR (50) NULL,
    [ApplianceOwnership_Washer]               NVARCHAR (50) NULL,
    [ApplianceOwnership_Dryer]                NVARCHAR (50) NULL,
    [ApplianceOwnership_Microwave]            NVARCHAR (50) NULL,
    [ApplianceOwnership_Stove]                NVARCHAR (50) NULL,
    CONSTRAINT [PK_Lease] PRIMARY KEY CLUSTERED ([Id] ASC)
);

