CREATE TABLE [dbo].[Property] (
    [Id]                              INT             NOT NULL,
    [AccountId]                       INT             NOT NULL,
    [BuyerAccountId]                  INT             NULL,
    [BuyerUserId]                     INT             NULL,
    [ExternalId]                      NVARCHAR (50)   NULL,
    [ProgramId]                       INT             NULL,
    [IsDwellCertified]                BIT             NOT NULL,
    [IsAllowOffer]                    BIT             NOT NULL,
    [IsAllowPreview]                  BIT             NOT NULL,
    [IsFeatured]                      BIT             NOT NULL,
    [IsRentGuaranteed]                BIT             NOT NULL,
    [AllowRentGuaranteedOptout]       BIT             NOT NULL,
    [IsSecuritized]                   BIT             NOT NULL,
    [IsHot]                           BIT             NOT NULL,
    [IsNew]                           BIT             NOT NULL,
    [IsBargain]                       BIT             NULL,
    [IsDiligenceVaultUnlocked]        BIT             NOT NULL,
    [IsPropertyManagerOfferRetain]    BIT             NULL,
    [IsHoa]                           BIT             NULL,
    [HasAudio]                        BIT             NOT NULL,
    [HasDiligenceVaultDocuments]      BIT             NOT NULL,
    [Market]                          INT             NOT NULL,
    [DaysOnMarket]                    INT             NULL,
    [Latitude]                        DECIMAL (9, 6)  NULL,
    [Longitude]                       DECIMAL (9, 6)  NULL,
    [PropertyName]                    NVARCHAR (50)   NULL,
    [Description]                     NVARCHAR (200)  NULL,
    [Highlights]                      NVARCHAR (400)  NULL,
    [MainImageUrl]                    NVARCHAR (1000) NULL,
    [PersonalProperties]              NVARCHAR (50)   NULL,
    [DiligenceVaultSummary]           NVARCHAR (50)   NULL,
    [FeaturedReason]                  NVARCHAR (50)   NULL,
    [Status]                          NVARCHAR (50)   NOT NULL,
    [AllowedFundingTypes]             NVARCHAR (50)   NULL,
    [AllowableSaleTypes]              NVARCHAR (50)   NULL,
    [Visibility]                      NVARCHAR (50)   NOT NULL,
    [PriceVisibility]                 NVARCHAR (50)   NOT NULL,
    [PropertyType]                    NVARCHAR (50)   NOT NULL,
    [CertificationLevel]              NVARCHAR (50)   NULL,
    [EscrowClosingDate]               DATE            NULL,
    [Address_Address1]                NVARCHAR (50)   NOT NULL,
    [Address_Address2]                NVARCHAR (50)   NULL,
    [Address_City]                    NVARCHAR (50)   NOT NULL,
    [Address_Country]                 NVARCHAR (50)   NULL,
    [Address_District]                NVARCHAR (50)   NULL,
    [Address_State]                   CHAR (2)        NOT NULL,
    [Address_Zip]                     CHAR (5)        NOT NULL,
    [Address_ZipPlus4]                CHAR (4)        NULL,
    [Financial_CapRate]               MONEY           NULL,
    [Financial_Occupancy]             NVARCHAR (50)   NULL,
    [Financial_IsSection8]            BIT             NULL,
    [Financial_LeaseStartDate]        DATETIME        NULL,
    [Financial_LeaseEndDate]          DATETIME        NULL,
    [Financial_ListPrice]             MONEY           NULL,
    [Financial_SalePrice]             MONEY           NULL,
    [Financial_MarketValue]           MONEY           NULL,
    [Financial_MonthlyHoa]            MONEY           NULL,
    [Financial_MonthlyManagementFees] MONEY           NULL,
    [Financial_MonthlyRent]           MONEY           NULL,
    [Financial_NetYield]              INT             NULL,
    [Financial_TurnOverFee]           MONEY           NULL,
    [Financial_RehabCosts]            MONEY           NULL,
    [Financial_RehabData]             MONEY           NULL,
    [Financial_YearlyInsuranceCost]   MONEY           NULL,
    [Financial_YearlyPropertyTaxes]   MONEY           NULL,
    [Financial_IsCashOnly]            BIT             NULL,
    [Physical_BathRooms]              DECIMAL (4, 2)  NULL,
    [Physical_BedRooms]               DECIMAL (4, 2)  NULL,
    [Physical_ParcelNumber]           NVARCHAR (50)   NULL,
    [Physical_IsPool]                 BIT             NULL,
    [Physical_LotSize]                INT             NULL,
    [Physical_SquareFeet]             INT             NULL,
    [Physical_Stories]                INT             NULL,
    [Physical_Units]                  INT             NULL,
    [Physical_YearBuilt]              INT             NULL,
    [Physical_ZipYearBuilt]           INT             NULL,
    [Score_ConditionScore]            NVARCHAR (50)   NULL,
    [Score_CrimeScore]                NVARCHAR (50)   NULL,
    [Score_NeighborhoodScore]         INT             NULL,
    [Score_OverallScore]              NVARCHAR (50)   NULL,
    [Score_QualityScore]              NVARCHAR (50)   NULL,
    [Score_SchoolScore]               NVARCHAR (50)   NULL,
    [Score_CharterSchoolScore]        NVARCHAR (50)   NULL,
    [Score_FloodRiskScore]            NVARCHAR (50)   NULL,
    [Score_WalkabilityScore]          NVARCHAR (50)   NULL,
    [Valuation_AvmBpiValue]           MONEY           NULL,
    [Valuation_AvmBpoAdjValue]        MONEY           NULL,
    [Valuation_AvmBpoDate]            DATETIME        NULL,
    [Valuation_RsAvmValue]            MONEY           NULL,
    [Valuation_RsAvmDate]             DATETIME        NULL,
    [Valuation_RsBpoMergeValue]       MONEY           NULL,
    [Manager]                         NVARCHAR (50)   NULL,
    [Seller]                          NVARCHAR (50)   NULL,
    [SellerBroker]                    NVARCHAR (50)   NULL,
    [Hoa]                             MONEY           NULL,
    [LeaseId]                         INT             NULL,
    [GoogleMapOption_HasStreetView]   BIT             NULL,
    [GoogleMapOption_PovHeading]      INT             NULL,
    [GoogleMapOption_PovPitch]        INT             NULL,
    [GoogleMapOption_PovLatitude]     DECIMAL (9, 6)  NULL,
    [GoogleMapOption_PovLongitude]    DECIMAL (9, 6)  NULL,
    [InspectionType]                  NVARCHAR (50)   NULL,
    CONSTRAINT [PK_Property] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Property_Lease] FOREIGN KEY ([LeaseId]) REFERENCES [dbo].[Lease] ([Id])
);

