// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RoofstockSolution
{
    public partial class Lease
    {
        public Lease()
        {
            Properties = new HashSet<Property>();
        }

        public int Id { get; set; }
        public LeaseSummary LeaseSummary { get; set; }
        public UtilitiesOwnership UtilitiesOwnership { get; set; }
        public ApplianceOwnership ApplianceOwnership { get; set; }

        public virtual ICollection<Property> Properties { get; set; }
    }
}