// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RoofstockSolution
{
    public partial class Property
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int? BuyerAccountId { get; set; }
        public int? BuyerUserId { get; set; }
        public string ExternalId { get; set; }
        public int? ProgramId { get; set; }
        public bool IsDwellCertified { get; set; }
        public bool IsAllowOffer { get; set; }
        public bool IsAllowPreview { get; set; }
        public bool IsFeatured { get; set; }
        public bool IsRentGuaranteed { get; set; }
        public bool AllowRentGuaranteedOptout { get; set; }
        public bool IsSecuritized { get; set; }
        public bool IsHot { get; set; }
        public bool IsNew { get; set; }
        public bool? IsBargain { get; set; }
        public bool IsDiligenceVaultUnlocked { get; set; }
        public bool? IsPropertyManagerOfferRetain { get; set; }
        public bool? IsHoa { get; set; }
        public bool HasAudio { get; set; }
        public bool HasDiligenceVaultDocuments { get; set; }
        public int Market { get; set; }
        public int? DaysOnMarket { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public string PropertyName { get; set; }
        public string Description { get; set; }
        public string Highlights { get; set; }
        public string MainImageUrl { get; set; }
        public string PersonalProperties { get; set; }
        public string DiligenceVaultSummary { get; set; }
        public string FeaturedReason { get; set; }
        public string Status { get; set; }
        public string AllowedFundingTypes { get; set; }
        public string AllowableSaleTypes { get; set; }
        public string Visibility { get; set; }
        public string PriceVisibility { get; set; }
        public string PropertyType { get; set; }
        public string CertificationLevel { get; set; }
        public DateTime? EscrowClosingDate { get; set; }
        public Address Address { get; set; }
        public Financial Financial { get; set; }
        public Physical Physical { get; set; }
        public Score Score { get; set; }
        public Valuation Valuation { get; set; }
        public string Manager { get; set; }
        public string Seller { get; set; }
        public string SellerBroker { get; set; }
        public decimal? Hoa { get; set; }
        public int? LeaseId { get; set; }
        public GoogleMapOption GoogleMapOption { get; set; }
        public string InspectionType { get; set; }

        public virtual Lease Lease { get; set; }
    }
}